#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     motorJ,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_2,     motorK,        tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S2_C1_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

#define deadband_size 0 //If the joystick isn't this far from 0, it's set to 0

#define motor_left_front   motor[motorG]
#define motor_left_middle  motor[motorH]
#define motor_left_rear    motor[motorI]
#define motor_right_front  motor[motorD]
#define motor_right_middle motor[motorE]
#define motor_right_rear   motor[motorF]
#define motor_intake       motor[motorJ]
#define motor_six_bar      motor[motorK]

#define servo_hopper  servo[servo1]

#define motor_max 100
#define motor_min -100
#define expFactor 1.037003976

task main() {
	int _powerLeft = 0;
	int _powerRight = 0;
	servo_hopper = 24;
	//bool _latchDown = false;
	//int _previousLatchInput = 0; //If this is differnt thean the current input, we know the button has just been pushed

	while(true) {
		getJoystickSettings(joystick);

		if(joystick.joy1_y1 >= 0) {
			_powerLeft = pow(expFactor, joystick.joy1_y1) - 1;
		} else {
			_powerLeft = -1 * (pow(expFactor, -1 * joystick.joy1_y1) - 1);
		}

		if(joystick.joy1_y2 >= 0) {
			_powerRight = pow(expFactor, joystick.joy1_y2) - 1;
		} else {
			_powerRight = -1 * (pow(expFactor, -1 * joystick.joy1_y2) - 1);
		}

		/*if (joy1Btn(8) == 1 && _previousLatchInput == 0) _latchDown = !_latchDown;

		servo[servo1] = (_latchDown) ? servo_up : servo_down;

		//servo[servo1] = servo_down;*/

		//If any motor is within 5 units of 0, set it to 0
		/* if (abs(_powerLeft) <= deadband_size) {
			_powerLeft = 0;
		}
		if (abs(_powerRight) <= deadband_size) {
			_powerRight = 0;
		} */

		if (_powerLeft > motor_max) { _powerLeft = motor_max; }
		if (_powerLeft < motor_min) { _powerLeft = motor_min; }
		if (_powerRight > motor_max) { _powerRight = motor_max; }
		if (_powerRight < motor_min) { _powerRight = motor_min; }

		motor_left_front   = _powerLeft;
		motor_left_middle  = _powerLeft;
		motor_left_rear    = _powerLeft;
		motor_right_front  = _powerRight;
		motor_right_middle = _powerRight;
		motor_right_rear   = _powerRight;

		//_previousLatchInput = joy1Btn(8);
		if(joy1Btn(6) == 1) motor_six_bar = 100;
		else if(joy1Btn(8) == 1) motor_six_bar = -10;
		else motor_six_bar = 0;

		if(joy1Btn(5) == 1) motor_intake = 100;
		else if(joy1Btn(7) == 1) motor_intake = -100;
		else motor_intake = 0;

		if(joy1Btn(4) == 1 && servo_hopper < 255) servo_hopper += 5;
		else if(joy1Btn(2) == 1 && servo_hopper > 0) servo_hopper -= 5;
	}
}
