#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

#define deadband_size 0 //If the joystick isn't this far from 0, it's set to 0
#define motor_left motor[motorE]
#define motor_right motor[motorD]
#define motor_max 100
#define motor_min -100
#define expFactor 1.037003976
#define servo_down 200
#define servo_up 255

task main()
{
	int _powerLeft = 0;
	int _powerRight = 0;
	bool _latchDown = false;
	int _previousLatchInput = 0; //If this is differnt thean the current input, we know the button has just been pushed

	while(true) {
		getJoystickSettings(joystick);

		if(joystick.joy1_y1 >= 0) {
			_powerLeft = pow(expFactor, joystick.joy1_y1) - 1;
		} else {
			_powerLeft = -1 * (pow(expFactor, -1 * joystick.joy1_y1) - 1);
		}

		if(joystick.joy1_y2 >= 0) {
			_powerRight = pow(expFactor, joystick.joy1_y2) - 1;
		} else {
			_powerRight = -1 * (pow(expFactor, -1 * joystick.joy1_y2) - 1);
		}

		if (joy1Btn(8) == 1 && _previousLatchInput == 0) _latchDown = !_latchDown;

		servo[servo1] = (_latchDown) ? servo_up : servo_down;

		//servo[servo1] = servo_down;

		//If any motor is within 5 units of 0, set it to 0
		/* if (abs(_powerLeft) <= deadband_size) {
			_powerLeft = 0;
		}
		if (abs(_powerRight) <= deadband_size) {
			_powerRight = 0;
		} */

		if (_powerLeft > motor_max) { _powerLeft = motor_max; }
		if (_powerLeft < motor_min) { _powerLeft = motor_min; }
		if (_powerRight > motor_max) { _powerRight = motor_max; }
		if (_powerRight < motor_min) { _powerRight = motor_min; }

		motor_left = _powerLeft;
		motor_right = _powerRight;
		motor[motorG] = _powerLeft;
		motor[motorF] = _powerRight;

		_previousLatchInput = joy1Btn(8);
	}
}
