#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     Drive_Left_1,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     Drive_Left_2,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     Drive_Right_1, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     Drive_Right_2, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     Elevator_1,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     Elevator_2,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     Intake,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorK,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define motor_max 100
#define motor_min 0
#define expFactor 1.037003976 //This number, raised to the power of joystick input, equals motor power

#define btn_elevator_up 5
#define btn_elevator_down 7
#define btn_intake_in 4
#define btn_intake_out 6

#define spd_elevator 100
#define spd_intake 100

#include "JoystickDriver.c"

task main()
{
        int _powerLeft = 0;
        int _powerRight = 0;
        int _powerElevator = 0;
        int _powerIntake = 0;

        while(true) {

                getJoystickSettings(joystick);

                if (joystick.joy1_y1 >= 0) {
                        _powerLeft = pow(expFactor, joystick.joy1_y1) - 1;
                } else {
                        _powerLeft = -1 * (pow(expFactor, -1 * joystick.joy1_y1) - 1);
                }

                if (joystick.joy1_y2 >= 0) {
                        _powerRight = pow(expFactor, joystick.joy1_y2) - 1;
                } else {
                        _powerRight = -1 * (pow(expFactor, -1 * joystick.joy1_y2) - 1);
                }

                if (joy1Btn(btn_elevator_up) == 1) {
                        _powerElevator = spd_elevator;
                } else if (joy1Btn(btn_elevator_down) == 1) {
                        _powerElevator = -1 * spd_elevator;
                } else {
                        _powerElevator = 0;
                }

                if (joy1Btn(btn_intake_in) == 1) {
                        _powerIntake = spd_intake;
                } else if (joy1Btn(btn_intake_out) == 1) {
                        _powerIntake = -1 * spd_intake;
                } else {
                        _powerIntake = 0;
                }

                if (_powerLeft > motor_max) { _powerLeft = motor_max; }
                if (_powerLeft < motor_min) { _powerLeft = motor_min; }
                if (_powerRight > motor_max) { _powerRight = motor_max; }
                if (_powerRight < motor_min) { _powerRight = motor_min; }

                motor[Drive_Left_1] = _powerLeft;
                motor[Drive_Left_2] = _powerRight;
                motor[Drive_Right_1] = _powerLeft;
                motor[Drive_Right_2] = _powerRight;
                motor[Intake] = _powerIntake;
                motor[Elevator_1] = _powerElevator;
                motor[Elevator_2] = _powerElevator;
        }
}
