#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "JoystickDriver.c"
#define dampen 5 //If the joystick isn't this far from 0, it's set to 0
#define motor_left motor[motorD]
#define motor_right motor[motorE]
#define motor_max 100
#define motor_min -100

//Arcade-style steering with one stick

task main()
{
	int _powerLeft = 0;
	int _powerRight = 0;
	while(true) {
		getJoystickSettings(joystick);
		_powerLeft = joystick.joy1_y1 + joystick.joy1_x1;
		_powerRight = joystick.joy1_y1 - joystick.joy1_x1;
		if (_powerLeft > motor_max) _powerLeft = motor_max;
		if (_powerLeft < motor_min) _powerLeft = motor_min;
		if (_powerRight > motor_max) _powerRight = motor_max;
		if (_powerRight < motor_min) _powerRight = motor_min;
		motor_left = _powerLeft;
		motor_right = _powerRight;
	}
}
