#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "JoystickDriver.c"
#define dampen 5 //If the joystick isn't this far from 0, it's set to 0

task main()
{
	while(true) {
		getJoystickSettings(joystick);

		//Joystick 1: Left motor
		if (abs(joystick.joy1_y1) > dampen) {
			motor[motorD] = joystick.joy1_y1;
		} else {
			motor[motorD] = 0;
		}

		//Joystick 2: Right motor
		if (abs(joystick.joy1_y2) > dampen) {
			motor[motorE] = joystick.joy1_y2;
		} else {
			motor[motorE] = 0;
		}
	}
}
