#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  HTServo)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C2_1,     motorDriveLR,  tmotorTetrix, openLoop, reversed, driveLeft)
#pragma config(Motor,  mtr_S1_C2_2,     motorDriveLM,  tmotorTetrix, openLoop, reversed, driveLeft)
#pragma config(Motor,  mtr_S1_C3_1,     motorDriveRR,  tmotorTetrix, openLoop, driveRight)
#pragma config(Motor,  mtr_S1_C3_2,     motorDriveLF,  tmotorTetrix, openLoop, reversed, driveLeft)
#pragma config(Motor,  mtr_S2_C1_1,     motorLift1,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C1_2,     motorLift2,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     motorDriveRM,  tmotorTetrix, openLoop, driveRight)
#pragma config(Motor,  mtr_S2_C2_2,     motorDriveRF,  tmotorTetrix, openLoop, driveRight)
#pragma config(Servo,  srvo_S1_C1_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_1,    servo7,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_2,    servo8,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo9,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "lib\PowerScale.c"
#include "lib\4211Lib_PID.h"

#define MOTOR_TICKS_PER_REV		1120

// ARM constants and state //
#define LIFT_GEAR_REDUCTION				1
#define LIFT_STAGES								4
#define LIFT_SPROCKET_TEETH				10
#define LIFT_CHAIN_PITCH_INCHES		0.25
#define LIFT_CM_PER_REV						(LIFT_SPROCKET_TEETH * LIFT_CHAIN_PITCH_INCHES * 2.54)
#define LIFT_TICKS_TO_CM 	    		(LIFT_STAGES * (LIFT_CM_PER_REV / MOTOR_TICKS_PER_REV))
#define LIFT_MAX_CM						120
#define LIFT_MIN_CM						0
#define LIFT_MAX_POWER_UP			20
#define LIFT_MAX_POWER_DOWN   -10
#define LIFT_KP 1.0
#define LIFT_KI 0.0
#define LIFT_KD 0.0

float _liftPosition, _liftPIDOutput, _liftPower;
PIDRefrence _liftPID;

// INTAKE constants //
#define INTAKE_TILT_SERVO_DEGREES	  180
#define INTAKE_TILT_MAX_DEGREES 		40
#define INTAKE_TILT_MIN_DEGREES 		0

// HOPPER constants //
#define HOPPER_TILT_SERVO_DEGREES	  180
#define HOPPER_TILT_MAX_DEGREES 		20
#define HOPPER_TILT_MIN_DEGREES 		0
#define HOPPER_RAMP_SERVO_DEGREES		180
#define HOPPER_RAMP_MAX_DEGREES			90
#define HOPPER_RAMP_MIN_DEGREES			0

// control function prototypes //
void Drive_setPower(int left, int right);
void Lift_setPosition(int cm);
//void Intake_setTilt(int degrees);
//void Intake_setPower(int power);
//void Hopper_setTilt(int degrees);
//void Hopper_setRamp(int degrees);

void Robot_initialize() {
	// initialize the lift //
	nMotorEncoder[motorLift1] = 0;
	_liftPID = addNewPID(LIFT_KP, LIFT_KI, LIFT_KD, &_liftPosition, &_liftPIDOutput);

  // start PID //
	setPIDTaskSettings(Hz_200, T3);
	startTask(pidHandler);
	while(!isPIDTaskReady) { } // wait for PID task to start //
}

task main() {
	Robot_initialize();
	//waitForStart();

	while(true) {
		getJoystickSettings(joystick);
		Drive_setPower(getScaledPower(joystick.joy1_y1), getScaledPower(joystick.joy1_y2));

		_liftPosition = nMotorEncoder[motorLift1] * LIFT_TICKS_TO_CM;
		_liftPower    = trim(_liftPIDOutput, LIFT_MAX_POWER_UP, LIFT_MAX_POWER_DOWN);
		//motor[motorLift1] = _liftPower;
		//motor[motorLift2] = _liftPower;

		if(joy1Btn(6)) {
		  motor[motorLift1] = 100;
		  motor[motorLift2] = 100;
			//Lift_setPosition(60);
	  } else if(joy1Btn(8)) {
	    motor[motorLift1] = -50;
	    motor[motorLift2] = -50;
	  	//Lift_setPosition(0);
		} else {
			motor[motorLift1] = 0;
			motor[motorLift2] = 0;
		}

		/*if(joy1Btn(5)) {
			Intake_setTilt(20);
			Intake_setPower(100);
		} else if(joy1Btn(7)) {
			Intake_setTilt(20);
			Intake_setPower(-100);
		} else {
			Intake_setTilt(0);
			Intake_setPower(0);
		}

		if(joy1Btn(4)) {
			Hopper_setTilt(20);
		} else {
			Hopper_setTilt(0);
		}*/
	}
}

void Drive_setPower(int left, int right) {
	left  = trim(left,  100, -100);
	right = trim(right, 100, -100);
	motor[motorDriveLF] = left;
	motor[motorDriveLM] = left;
	motor[motorDriveLR] = left;
	motor[motorDriveRF] = right;
	motor[motorDriveRM] = right;
	motor[motorDriveRR] = right;
}

void Lift_setPosition(int cm) {
	cm = trim(cm, LIFT_MAX_CM, LIFT_MIN_CM);
	setPIDTarget(_liftPID, cm);
}

/*void Intake_setTilt(int degrees) {
	degrees = trim(degrees, INTAKE_TILT_MAX_DEGREES - INTAKE_TILT_MIN_DEGREES, 0) + INTAKE_TILT_MIN_DEGREES;
	degrees *= 255 / INTAKE_TILT_SERVO_DEGREES;
	servo[servoIntakeTilt1] = degrees;
	servo[servoIntakeTilt2] = 127 - degrees;

}

void Intake_setPower(int power) {
	power = trim(power, 100, -100) * 127 / 100;
	servo[servoIntakeRoller1] = power;
	servo[servoIntakeRoller2] = 127 - power;
}

void Hopper_setTilt(int degrees) {
	degrees = trim(degrees, HOPPER_TILT_MAX_DEGREES - HOPPER_TILT_MIN_DEGREES, 0) + HOPPER_TILT_MIN_DEGREES;
	degrees *= 255 / HOPPER_TILT_SERVO_DEGREES;
	servo[servoHopperTilt1] = degrees;
	servo[servoHopperTilt2] = 127 - degrees;
}

void Hopper_setRamp(int degrees) {
	degrees = trim(degrees, HOPPER_RAMP_MAX_DEGREES - HOPPER_RAMP_MIN_DEGREES, 0) + HOPPER_RAMP_MIN_DEGREES;
	degrees *= 255 / HOPPER_RAMP_SERVO_DEGREES;
	servo[servoHopperRamp] = degrees;
}*/
