#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorDriveRR,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorArm,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorDriveRF,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorDriveRM,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorDriveLF,  tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     motorDriveLM,  tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_1,     motorDriveLR,  tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_2,     motorIntake,   tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S2_C1_1,    servoHopper,          tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    servoLatch,           tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "lib\PowerScale.c"
#include "lib\4211Lib_PID.h"

// Neverest 40 Motor //
#define MOTOR_TICKS_PER_REV		1120

// ARM constants and state //
#define ARM_GEAR_REDUCTION		8
#define ARM_TICKS_TO_DEGREES 	(360.0 / (MOTOR_TICKS_PER_REV * ARM_GEAR_REDUCTION))
#define ARM_MAX_DEGREES				118
#define ARM_MIN_DEGREES				0
#define ARM_MAX_POWER_UP			100
#define ARM_MAX_POWER_DOWN    -5

#define ARM_KP 	5.0
#define ARM_KI 	0.0
#define ARM_KD 	0.0

#define ARM_DEGREES_FLOOR  0
#define ARM_DEGREES_30CM   45
#define ARM_DEGREES_60CM   75
#define ARM_DEGREES_90CM   115

#define LATCH_DOWN	1
#define LATCH_UP		213

float armDegrees, armPIDOutput, armPower;
PIDRefrence armPID;

// HOPPER constants //
#define HOPPER_SERVO_DEGREES	180
#define HOPPER_MAX_DEGREES 		90
#define HOPPER_MIN_DEGREES 		0

// control function prototypes //
void Drive_setPower(int left, int right);
void Arm_setPosition(int degrees);
void Intake_setPower(int power);
void Hopper_setTilt(int degrees);

void Robot_initialize() {
	// initialize the arm //
	nMotorEncoder[motorArm] = 0;
	armPID = addNewPID(ARM_KP, ARM_KI, ARM_KD, &armDegrees, &armPIDOutput);

  // start PID //
	setPIDTaskSettings(Hz_200, T3);
	startTask(pidHandler);
	while(!isPIDTaskReady) { } // wait for PID task to start //

	// initialize latch //
	servo[servoLatch] = LATCH_UP;
}

task main() {
	Robot_initialize();
	//waitForStart();
  Arm_setPosition(ARM_DEGREES_FLOOR);

  bool latchPressed = false;
	while(true) {
		getJoystickSettings(joystick);
		Drive_setPower(getScaledPower(joystick.joy1_y1), getScaledPower(joystick.joy1_y2));

		armDegrees = nMotorEncoder[motorArm] * ARM_TICKS_TO_DEGREES;
		armPower   = trim(armPIDOutput, ARM_MAX_POWER_UP, ARM_MAX_POWER_DOWN);
		motor[motorArm] = armPower;
		//motor[motorArm] = joystick.joy1_y1;

		if(joy1Btn(4)) {
			Arm_setPosition(ARM_DEGREES_90CM);
		} else if(joy1Btn(1)) {
			Arm_setPosition(ARM_DEGREES_60CM);
		} else if(joy1Btn(2)) {
			Arm_setPosition(ARM_DEGREES_30CM);
	  } else if(joy1Btn(8)) {
	  	Arm_setPosition(ARM_DEGREES_FLOOR);
		}

		if(joy1Btn(5)) {
			Intake_setPower(100);
		} else if(joy1Btn(7)) {
			Intake_setPower(-60);
		} else {
			Intake_setPower(0);
		}

		if(joy1Btn(6)) {
			Hopper_setTilt(60);
		} else {
			Hopper_setTilt(40);
		}

		if(joy1Btn(3) && !latchPressed) {
			servo[servoLatch] = ServoValue[servoLatch] == LATCH_DOWN? LATCH_UP: LATCH_DOWN;
			latchPressed = true;
		} else if(!joy1Btn(3)) {
			latchPressed = false;
		}
		//servo[servoLatch] = 128 + joystick.joy1_y1;
	}
}

void Drive_setPower(int left, int right) {
	left  = trim(left,  100, -100);
	right = trim(right, 100, -100);
	motor[motorDriveLF] = left;
	motor[motorDriveLM] = left;
	motor[motorDriveLR] = left;
	motor[motorDriveRF] = right;
	motor[motorDriveRM] = right;
	motor[motorDriveRR] = right;
}

void Arm_setPosition(int degrees) {
	degrees = trim(degrees, ARM_MAX_DEGREES, ARM_MIN_DEGREES);
	setPIDTarget(armPID, degrees);
}

void Intake_setPower(int power) {
	power = trim(-power, 100, -100);
	motor[motorIntake] = power;
}

void Hopper_setTilt(int degrees) {
	degrees = trim(degrees, HOPPER_MAX_DEGREES, HOPPER_MIN_DEGREES);
	servo[servoHopper] = degrees * 255 / HOPPER_SERVO_DEGREES;
}
