#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorRF,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorRM,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorRR,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     motorLF,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorLM,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorLR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     motorIntake,   tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_2,     motor6bar,     tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S2_C1_1,    servoHopper,          tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "lib\PowerScale.c"

long encoder6bar = 0;

void setDrivePower(int left, int right) {
	motor[motorLF] = left;
	motor[motorLM] = left;
	motor[motorLR] = left;
	motor[motorRF] = right;
	motor[motorRM] = right;
	motor[motorRR] = right;
}


task main() {

	while(true) {
		getJoystickSettings(joystick);
		setDrivePower(getScaledPower(joystick.joy1_y1), getScaledPower(joystick.joy1_y2));

		if(joy1Btn(6) == 1) {
			motor[motor6bar] = 100;
	  } else if(joy1Btn(8) == 1) {
	  	motor[motor6bar] = -10;
		} else {
			motor[motor6bar] = 0;
		}
		encoder6bar = nMotorEncoder[motor6bar];

		if(joy1Btn(5) == 1) {
			motor[motorIntake] = 100;
		} else if(joy1Btn(7) == 1) {
			motor[motorIntake] = -100;
		} else {
			motor[motorIntake] = 0;
		}

		if(joy1Btn(4) == 1 && servo[servoHopper] < 255) {
			servo[servoHopper] += 5;
		} else if(joy1Btn(2) == 1 && servo[servoHopper] > 0) {
			servo[servoHopper] -= 5;
		}
	}

}
